/* Auto-generated INT8 HardTanh BMS NN residual weights.
 *
 * Generated by bms_nn_quantize_int8_hardtanh.py.
 *
 * Model:
 *   Dense -> HardTanh -> Dense -> HardTanh -> Dense
 *
 * INT8 reference path:
 *   int8 activations, int8 weights, int32 accumulators, int32 biases.
 *   HardTanh maps to Q7 clamp [-127,127].
 *
 * CMSIS-NN/MVE migration:
 *   The dense layers can be replaced with arm_fully_connected_s8-style kernels.
 *   Gate/deadband/vlim safety logic remains outside the dense inference block.
 */

#ifndef BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_H_
#define BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_H_

#include <stdint.h>

#define BMS_NN_Q_N_IN 15
#define BMS_NN_Q_H1 16
#define BMS_NN_Q_H2 8

#define BMS_NN_Q_ACTIVATION_HARDTANH 1
#define BMS_NN_Q_ACT_MIN -127
#define BMS_NN_Q_ACT_MAX 127

#define BMS_NN_Q_INPUT_CLIP 2.0f
#define BMS_NN_Q_INPUT_SCALE 0.0157480315f
#define BMS_NN_Q_ACT_SCALE 0.00787401575f

#define BMS_NN_Q_V_CLAMP_V 0.04f
#define BMS_NN_Q_OUTPUT_GAIN 1.18676471f
#define BMS_NN_Q_OUTPUT_DEADBAND_V 0.0005f

#define BMS_NN_Q_OUTPUT_V_PER_ACC 7.90469101e-07f

/* Shape notes:
 * w1: [H1][N_IN], row-major by output channel.
 * b1: [H1], int32, scale=input_scale*w1_scale[channel].
 * l1_to_act_real_multiplier[channel] = input_scale*w1_scale[channel]/act_scale.
 *
 * w2: [H2][H1], row-major by output channel.
 * b2: [H2], int32, scale=act_scale*w2_scale[channel].
 * l2_to_act_real_multiplier[channel] = w2_scale[channel].
 *
 * w3: [1][H2], row-major.
 * b3: [1], int32, scale=act_scale*w3_scale[0].
 */

static const int8_t bms_nn_q_w1[240] = {
    40, -30, 29, -12, 7, 36, -7, 15, -11, 127, -9, 46,
    -42, 48, -38, 20, -47, 18, -7, 12, 28, -36, 49, 29,
    127, -32, -12, -29, -8, -24, 16, 54, 96, -105, 99, -88,
    105, -127, 93, -39, 46, 42, 19, 78, 102, -56, -106, 118,
    -47, 69, 2, -33, 53, -24, 127, -4, 11, 100, 30, -29,
    24, 44, 2, 7, -8, 23, 15, 12, 30, -127, -5, 12,
    -2, -28, -1, 3, -127, 38, 5, -70, 52, 91, -82, 38,
    112, 92, -53, -57, -9, 10, -56, 23, -20, -18, -21, 44,
    108, 81, -33, -92, -47, -78, -127, -36, -8, 107, -46, -86,
    -69, 39, -6, 6, 83, 114, -127, -43, -39, 95, 36, -31,
    51, 51, -127, 17, 14, 46, -38, -24, -5, -93, 42, 91,
    52, 51, 51, -3, -43, 98, -29, 54, 58, -15, -4, -44,
    127, 8, -12, -31, -71, -28, 8, 62, 127, 62, -22, 31,
    67, -91, 28, 111, -34, -80, 42, -3, 81, -27, 127, -80,
    12, 14, 47, -63, 12, 6, -97, 6, 17, -21, -16, 37,
    26, -20, 40, -25, -7, -9, -50, 16, 35, 127, -59, 24,
    70, -18, -28, -31, 10, -20, 6, -27, 28, -5, 3, -39,
    -127, 50, 55, -39, 23, -1, -18, 43, -60, -26, 63, -35,
    -23, 25, 20, -127, 14, 44, 26, -40, -35, 60, -13, 32,
    -24, -34, -13, -61, -10, 0, -127, -58, -26, 2, 49, -49
};

static const int32_t bms_nn_q_b1[16] = {
    2651, 1841, 4720, 1631, 423, -643, 1772, -3226,
    -3368, 3859, 7986, -3460, 1189, -2451, -80, 1739
};

static const float bms_nn_q_w1_scale[16] = {
    0.00384263072f, 0.00586014751f, 0.00213419781f, 0.00306496423f,
    0.00573485151f, 0.0027542011f, 0.00207898748f, 0.00233483057f,
    0.00356025912f, 0.00331676382f, 0.00203503915f, 0.00285029669f,
    0.0035319089f, 0.00518640946f, 0.00428691389f, 0.00309241287f
};

static const float bms_nn_q_l1_to_act_real_multiplier[16] = {
    0.00768526145f, 0.011720295f, 0.00426839562f, 0.00612992846f,
    0.011469703f, 0.0055084022f, 0.00415797496f, 0.00466966113f,
    0.00712051824f, 0.00663352764f, 0.0040700783f, 0.00570059339f,
    0.0070638178f, 0.0103728189f, 0.00857382778f, 0.00618482575f
};

static const int8_t bms_nn_q_w2[128] = {
    81, -127, 101, 14, -83, 100, 35, -110, -29, 91, 5, 112,
    -112, 87, 45, 5, 66, -25, -37, 127, -63, 82, -32, 17,
    -33, -14, 54, 2, 2, -34, 27, -45, 3, 89, 83, 122,
    -127, -93, -77, 12, -10, 114, 85, -122, 45, -45, 25, 45,
    99, 90, -44, 14, -127, -74, -90, -98, 12, 52, 58, -100,
    44, -85, -94, -14, -12, -23, -111, -34, 127, -33, -95, 11,
    117, -16, 36, 52, 5, 51, 104, -78, -127, 57, 51, -74,
    -17, 57, -67, -12, -22, -91, 21, 60, 127, -7, -67, -126,
    36, -106, 82, -104, -62, -68, 65, -65, 127, -50, -58, 68,
    -22, -45, 77, 29, -81, 4, -103, 11, -46, -9, -30, 66,
    72, 24, 37, 124, -22, 65, 127, 28
};

static const int32_t bms_nn_q_b2[8] = {
    -13040, -7188, -3911, 13122, 1700, 8668, 5710, -601
};

static const float bms_nn_q_w2_scale[8] = {
    0.00209574413f, 0.00289469558f, 0.00221505527f, 0.00238854256f,
    0.0024175252f, 0.00187471239f, 0.00261925665f, 0.00187872139f
};

static const float bms_nn_q_l2_to_act_real_multiplier[8] = {
    0.00209574413f, 0.00289469558f, 0.00221505527f, 0.00238854256f,
    0.0024175252f, 0.00187471239f, 0.00261925665f, 0.00187872139f
};

static const int8_t bms_nn_q_w3[8] = {
    3, 79, 42, 113, -117, 10, -127, -6
};

static const int32_t bms_nn_q_b3[1] = {
    -3074
};

static const float bms_nn_q_w3_scale[1] = {
    0.0021147742f
};

#endif /* BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_H_ */
