/* Auto-generated CMSIS-NN INT8 HardTanh BMS residual weights.
 *
 * Generated by bms_nn_quantize_int8_hardtanh_cmsis.py.
 *
 * Intended backend:
 *   FC1/FC2: arm_fully_connected_s8() + activation clamp [-127,127]
 *   FC3: manual int8/int32 accumulation -> residual voltage
 */

#ifndef BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_CMSIS_H_
#define BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_CMSIS_H_

#include <stdint.h>

#define BMS_NN_CMSIS_N_IN 15
#define BMS_NN_CMSIS_H1 16
#define BMS_NN_CMSIS_H2 8

#define BMS_NN_CMSIS_ACTIVATION_HARDTANH 1
#define BMS_NN_CMSIS_ACT_MIN -127
#define BMS_NN_CMSIS_ACT_MAX 127

#define BMS_NN_CMSIS_INPUT_CLIP 2.0f
#define BMS_NN_CMSIS_INPUT_SCALE 0.0157480315f
#define BMS_NN_CMSIS_ACT_SCALE 0.00787401575f

#define BMS_NN_CMSIS_V_CLAMP_V 0.04f
#define BMS_NN_CMSIS_OUTPUT_GAIN 1.18676471f
#define BMS_NN_CMSIS_OUTPUT_DEADBAND_V 0.0005f

/* CMSIS-NN arm_fully_connected_s8 quantization params. */
#define BMS_NN_CMSIS_FC1_MULT 1610825082
#define BMS_NN_CMSIS_FC1_SHIFT -6
#define BMS_NN_CMSIS_FC2_MULT 1591375726
#define BMS_NN_CMSIS_FC2_SHIFT -8

/* FC3 remains manual: pred_raw_V = acc3 * BMS_NN_CMSIS_OUTPUT_V_PER_ACC. */
#define BMS_NN_CMSIS_OUTPUT_V_PER_ACC 7.90469101e-07f

#define BMS_NN_CMSIS_W1_SCALE 0.00586014751f
#define BMS_NN_CMSIS_W2_SCALE 0.00289469558f
#define BMS_NN_CMSIS_W3_SCALE 0.0021147742f
#define BMS_NN_CMSIS_L1_REAL_MULT 0.011720295f
#define BMS_NN_CMSIS_L2_REAL_MULT 0.00289469558f

static const int8_t bms_nn_cmsis_w1[240] = {
    26, -19, 19, -8, 5, 24, -4, 10, -8, 83, -6, 30,
    -28, 32, -25, 20, -47, 18, -7, 12, 28, -36, 49, 29,
    127, -32, -12, -29, -8, -24, 6, 20, 35, -38, 36, -32,
    38, -46, 34, -14, 17, 15, 7, 28, 37, -29, -56, 62,
    -25, 36, 1, -17, 28, -12, 66, -2, 6, 52, 16, -15,
    23, 43, 2, 7, -8, 23, 15, 12, 29, -124, -5, 11,
    -2, -28, -1, 1, -60, 18, 2, -33, 24, 43, -38, 18,
    53, 43, -25, -27, -4, 5, -20, 8, -7, -6, -7, 16,
    38, 29, -12, -32, -17, -28, -45, -13, -3, 43, -18, -34,
    -27, 16, -3, 2, 33, 46, -51, -17, -16, 38, 14, -12,
    31, 31, -77, 11, 9, 28, -23, -15, -3, -57, 25, 55,
    32, 31, 31, -2, -25, 55, -16, 31, 33, -9, -2, -25,
    72, 4, -7, -17, -40, -16, 3, 21, 44, 21, -8, 11,
    23, -32, 10, 39, -12, -28, 15, -1, 28, -13, 62, -39,
    6, 7, 23, -31, 6, 3, -47, 3, 8, -10, -8, 18,
    16, -12, 24, -15, -4, -5, -30, 10, 21, 77, -36, 14,
    42, -11, -17, -28, 8, -18, 6, -24, 25, -5, 3, -35,
    -112, 44, 49, -35, 21, 0, -13, 32, -44, -19, 46, -26,
    -17, 18, 14, -93, 10, 32, 19, -30, -25, 32, -7, 17,
    -13, -18, -7, -32, -5, 0, -67, -30, -14, 1, 26, -26
};

static const int32_t bms_nn_cmsis_b1[16] = {
    1739, 1841, 1719, 853, 414, -302, 629, -1285,
    -2046, 2184, 2773, -1683, 717, -2169, -59, 918
};

static const int8_t bms_nn_cmsis_w2[128] = {
    59, -92, 73, 10, -60, 72, 25, -80, -21, 66, 3, 81,
    -81, 63, 32, 4, 66, -25, -37, 127, -63, 82, -32, 17,
    -33, -14, 54, 2, 2, -34, 27, -45, 3, 68, 63, 93,
    -97, -71, -59, 9, -8, 87, 65, -93, 34, -35, 19, 34,
    82, 74, -36, 12, -105, -61, -74, -81, 10, 43, 48, -83,
    37, -70, -77, -12, -10, -19, -92, -29, 106, -27, -80, 9,
    98, -14, 30, 43, 4, 43, 87, -65, -82, 37, 33, -48,
    -11, 37, -43, -8, -14, -59, 14, 39, 82, -5, -44, -81,
    33, -96, 75, -94, -56, -62, 59, -59, 115, -46, -52, 62,
    -19, -41, 70, 26, -52, 2, -67, 7, -30, -6, -19, 43,
    47, 16, 24, 80, -15, 42, 82, 18
};

static const int32_t bms_nn_cmsis_b2[8] = {
    -9441, -7188, -2993, 10827, 1420, 5614, 5166, -390
};

static const int8_t bms_nn_cmsis_w3[8] = {
    3, 79, 42, 113, -117, 10, -127, -6
};

static const int32_t bms_nn_cmsis_b3[1] = {
    -3074
};

#endif /* BMS_NN_RESIDUAL_WEIGHTS_INT8_HARDTANH_CMSIS_H_ */
